// frontend/react/src/App.jsx
import { useContext } from 'react';
import { StoreContext } from './store';

import List from './components/List';
import Form from './components/Form';
import Header from './components/Header';
import LoginForm from './components/Login';

const App = () => {
  const { state } = useContext(StoreContext);
  return (
    <>
      <Header />
      <div className="container">
        {state.auth.isLoggedIn ? (
          <>
            <div className="card px-3">
              <div className="card-body">
                <Form />
                <List />
              </div>
            </div>
          </>
        ) : (
          <>
            <p>
              Example app with login system using cookies. To login, use any
              username and the password <kbd>abcdef</kbd>
            </p>
            <LoginForm />
          </>
        )}
      </div>
    </>
  );
}

export default App;

// frontend/svelte/src/App.svelte
<script>
  import Header from './components/Header.svelte'
  import Form from './components/Form.svelte';
  import List from './components/List.svelte';
  import Login from './components/Login.svelte';

  import { loginStore } from './stores/login';
  import Card from './components/Card.svelte';
</script>

<main>
  <Header />
    {#if $loginStore.loggedIn}
      <Card title="Todos">
        <div class="flex flex-col">
          <Form />
          <List />
        </div>
      </Card>
    {:else}
      <p class="w-full text-center">
        To login, use any username and the password <kbd>abcdef</kbd>
      </p>
      <Login />
    {/if}
</main>

<style>
  
</style>
