// frontend/svelte/src/components/Form.svelte
<script>
  import { tick } from 'svelte';

  import { todos } from '../stores/todos.js';
  import Button from './Button.svelte';
  
  let title;
  let input;
  const handleClickButton = async () => {
    const id = crypto.randomUUID();
    todos.add(title, id);
    await tick();
    input.focus();
    title = ""
  }

  function init(el){
    el.focus()
  }
</script>

<div class="flex mb-4 overflow-hidden">
  <input
    type="text"
    class="form-control todo-list-input"
    placeholder="What do you need to do today?"
    bind:value={title}
    bind:this={input}
    use:init
  />
  <Button invert on:click={handleClickButton}>Add</Button>
</div>

// frontend/vue/src/components/Form.vue
<script setup>
import { ref } from "vue";
import { useStore } from "vuex";

const title = ref("");
console.log(title.value);

const store = useStore();

const createTodo = () => {
  console.log(title, title.value);
  store.dispatch("createTodo", title);
};
</script>

<template>
  <div class="hstack gap-3">
    <input
      type="text"
      className="form-control todo-list-input"
      placeholder="What do you need to do today?"
      v-model="title"
      @input="handleChange"
      @keyup.enter="createTodo"
    />
    <button
      @click="createTodo"
      className="add btn btn-primary font-weight-bold todo-list-add-btn"
    >
      Add
    </button>
  </div>
</template>
