// frontend/vue/src/components/List.vue
<script setup>
import { useStore } from "vuex";
import { computed } from "vue";
import IconDelete from "~icons/mdi/delete";
import { marked } from "marked";

const store = useStore();

console.log("Calling All Dispatch!");
store.dispatch("fetchAllTodos");

const todos = computed(() => store.state.todos);
console.log(todos);

const toggle = (id) => {
  store.dispatch("toggleTodo", id);
};

const deleteTodo = (id) => {
  store.dispatch("deleteTodo", id);
};
</script>

<template>
  <div class="list-wrapper">
    <ul class="d-flex flex-column-reverse todo-list">
      <li v-for="todo in todos" :key="todo.id">
        <div class="form-check">
          <label class="form-check-label">
            <input
              class="checkbox"
              v-model="todo.completed"
              type="checkbox"
              @click="toggle(todo.id)"
            />
            <span v-html="marked.parse(todo.title)" />
            <i class="input-helper" />
          </label>
        </div>
        <IconDelete
          class="remove mdi mdi-close-circle-outline"
          @click="deleteTodo(todo.id)"
        />
        <i />
      </li>
    </ul>
  </div>
</template>

// frontend/react/src/components/List.jsx
import { useContext, useEffect } from 'react';
import { StoreContext } from '../store';
import { marked } from 'marked';

const List = () => {
  const {state: { todos }, dispatch } = useContext(StoreContext);
  useEffect(() => {
    dispatch({
      type: 'FETCH_ALL_TODOS',
    });
  }, []);
  return (
    <div className="list-wrapper">
      <ul className="d-flex flex-column-reverse todo-list">
        {todos.map((el) => (
          <li
            key={el.id}
            className={el.isComplete ? 'completed' : ''}
            style={{
              textDecoration: el.isComplete ? 'line-through' : 'none',
            }}
          >
            <div className="form-check">
              <label className="form-check-label">
                <input
                  className="checkbox"
                  defaultChecked={el.isComplete}
                  type="checkbox"
                  onClick={() =>
                    dispatch({
                      type: 'TOGGLE_TODO',
                      payload: el.id,
                    })
                  }
                />
                <span dangerouslySetInnerHTML={{__html: marked.parse(el.title)}}></span>
                <i className="input-helper" />
              </label>
            </div>
            <i
              className="remove mdi mdi-close-circle-outline"
              onClick={() =>
                dispatch({
                  type: 'DELETE_TODO',
                  payload: el.id,
                })
              }
            />
          </li>
        ))}
      </ul>
    </div>
  );
};

export default List;
