// frontend/solidjs/src/store.tsx
import { createContext, useContext, Component } from 'solid-js';
import { createStore } from 'solid-js/store';

import type { Todo, AppStore, State } from './types';

const AppContext = createContext<AppStore>();

export const AppProvider: Component = (props) => {
  const [state, setState] = createStore<State>({
    auth: {
      isLoggedIn: false,
      username: '',
    },
    todos: [] as Todo[],
  });

  const methods = {
    login(username: string, password: string) {
      fetch('/api/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ username, password }),
      })
        .then((res) => res.json())
        .then((res) => {
          if (res.success) {
            setState('auth', { isLoggedIn: true, username });
            methods.fetchAllTodos();
          } else {
            console.error(res.error);
          }
        });
    },
    logout() {
      fetch('/api/logout')
        .then((res) => res.json())
        .then((res) => {
          if (res.success) {
            setState('auth', { isLoggedIn: false, username: '' });
            methods.setAllTodos([]);
          } else {
            console.error(res.error);
          }
        });
    },
    getUserInfo() {
      fetch('/api/me')
        .then((res) => res.json())
        .then((res) => {
          if (res.success) {
            setState('auth', { isLoggedIn: true, username: res.username });
            methods.fetchAllTodos();
          } else {
            console.error(res.error);
          }
        });
    },

    // Todo-related routes, for implementation example.
    setAllTodos: (todos: Todo[]) => {
      setState('todos', todos);
    },
    fetchAllTodos(filter?: string) {
      const endpoint =
        filter && filter.length > 0
          ? `/api/search/${encodeURI(filter)}`
          : '/api/todos';

      fetch(endpoint)
        .then((r) => r.json())
        .then(methods.setAllTodos);
    },
    addTodo: (newTodo: Todo) => {
      fetch('/api/todos', {
        method: 'POST',
        body: JSON.stringify(newTodo),
      })
        .then(() => {
          setState('todos', (existingTodos) => existingTodos.concat(newTodo));
        })
        .catch((e) => console.log(e));
    },
    deleteTodo: (id: string) => {
      console.log(id);
      fetch('/api/todos/' + id, { method: 'DELETE' })
        .then(() => {
          setState('todos', (prev) =>
            prev.filter((item: Todo) => item.id !== id),
          );
        })
        .catch((e) => console.log(e));
    },
    toggleTodo: (id: string) => {
      fetch('/api/todos/toggle/' + id)
        .then((res) => res.json())
        .then((todo) => {
          setState('todos', (prev) =>
            prev.map((item: Todo) => (item.id === id ? todo : item)),
          );
        })
        .catch((e) => console.log(e));
    },
  };

  const store = [state, methods] as AppStore;

  return (
    <AppContext.Provider value={store}>{props.children}</AppContext.Provider>
  );
};

export const useStore = (): AppStore => useContext(AppContext) as AppStore;

// frontend/react/src/store.js
import React, { createContext, useState } from "react";

export const StoreContext = createContext();

const initiaState = {
  isPageLoaded: false,
  auth: {
    isLoggedIn: false,
    username: "",
  },
  todos: [],
};

const reducer = async (state, action) => {
  switch (action.type) {
    case "ADD_TODO":
      try {
        await fetch("/api/todos", {
          method: "POST",
          body: JSON.stringify(action.payload),
        });
        return { ...state, todos: state.todos.concat(action.payload) };
      } catch(err) {
        console.error(err);
        return {
          ...state,
          err
        }
      }
    case "DELETE_TODO":
      try {
        await fetch("/api/todos/" + action.payload, { method: "DELETE" });
        return {
          ...state,
          todos: state.todos.filter((a) => a.id !== action.payload),
        };
      } catch(err) {
        return {
          ...state,
          err,
        };
      }
    case "TOGGLE_TODO":
      try {
        await fetch("/api/todos/toggle/" + action.payload)
          .then((res) => res.json());
        return {
          ...state,
          todos: state.todos.map((a) => ({
            ...a,
            isComplete: a.id === action.payload ? !a.isComplete : a.isComplete,
          })),
        };
      } catch(err) {
        return {
          ...state,
          err,
        };
      }
    case "FETCH_ALL_TODOS":
      const allTodoRes = await fetch("/api/todos").then(res => res.json());
      return { ...state, todos: allTodoRes };
    case "LOGIN":
      const loginRes = await fetch("/api/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username: action.payload.username, password: action.payload.password }),
      }).then((res) => res.json())
      if (loginRes.success) {
        return {
          ...state,
          auth: { isLoggedIn: true, username: action.payload.username },
          todos: []
        };
      } else {
        console.error(loginRes.error);
      }
      return state;
    case "LOGOUT":
      const logoutRes = await fetch("/api/logout").then((res) => res.json());
      if (logoutRes.success) {
        return {
          ...state,
          auth: { isLoggedIn: false, username: "" },
        };
      } else {
        console.error(logoutRes.error);
      }
      break;
    case "GET_USER_INFO":
      const tempState = { ...state }
      if (tempState.isPageLoaded) return state;
      tempState.isPageLoaded = true;
      const userInfo = await fetch("/api/me").then((res) => res.json());
      if (userInfo.success) {
        tempState.auth = { isLoggedIn: true, username: userInfo.username };
      } else {
        console.error(userInfo.error);
      }
      return tempState;
    default:
      return state;
  }
};

const useAsyncReducer = (reducer, initialState = null) => {
  const [state, setState] = useState(initialState);

  const dispatch = async (action) => {
    const result = reducer(state, action);
    if (typeof result.then === "function") {
      try {
        const newState = await result;
        setState(newState);
      } catch (err) {
        setState({ ...state, error: err });
      }
    } else {
      setState(result);
    }
  };

  return [state, dispatch];
};

const Store = ({ children }) => {
  const [state, dispatch] = useAsyncReducer(reducer, initiaState);
  return (
    <StoreContext.Provider value={[state, dispatch]}>
      {children}
    </StoreContext.Provider>
  );
};

export default Store;
