// frontend/react/src/App.jsx
import { useContext } from 'react';
import { StoreContext } from './store';

import List from './components/List';
import Form from './components/Form';
import Header from './components/Header';
import LoginForm from './components/Login';

const App = () => {
  const { state } = useContext(StoreContext);
  return (
    <>
      <Header />
      <div className="container">
        {state.auth.isLoggedIn ? (
          <>
            <div className="card px-3">
              <div className="card-body">
                <Form />
                <List />
              </div>
            </div>
          </>
        ) : (
          <>
            <p>
              Example app with login system using cookies. To login, use any
              username and the password <kbd>abcdef</kbd>
            </p>
            <LoginForm />
          </>
        )}
      </div>
    </>
  );
}

export default App;

// frontend/solidjs/src/App.jsx
import { Show } from 'solid-js';
import { Transition } from 'solid-transition-group';

import List from './Components/List'
import Form from './Components/Form';
import Header from './Components/Header';

import { useStore } from './store';

const App = () => {
  const [state] = useStore();

  return (
    <>
      <Header />
      <Transition name="fade">
        <Show when={state.auth.isLoggedIn}>
          <div class="container">
            <div class="card px-3">
              <div class="card-body">
                <h4 class="card-title">Your Todo List</h4>
                <Form />
                <List />
              </div>
            </div>
          </div>
        </Show>
      </Transition>
    </>
  );
};

export default App;
